from youtube_transcript_api import YouTubeTranscriptApi
from datetime import timedelta
from pathlib import Path
import re
from app.config.logging import logger

# services
from app.services.youtube_data import *
from app.services.gemini_notes import get_notes

# db and models
from app.db.models import *
from app.db.base import SessionLocal

# keyboards
from app.bot.keyboards.notes_kb import *

"""---------------------------------------------------------------------------------------------------------------"""
# FUNCTION TO CHOOSE THE TRANSCRIPT
def choose_transcript(video_id):
    # Initialise the youtube transcript
    ytt_api = YouTubeTranscriptApi()
    transcript_list = ytt_api.list(video_id)

    # Set up the transcript variables
    auto_generated_transcript = None
    manual_transcript = None

    # Choose the correct transcript object
    for transcript in transcript_list:
        if transcript.is_generated == False:
            # If a manual english transcript exists then choose that
            if transcript.language_code.startswith("en"):
                manual_transcript = transcript
                break
            # If a manual non english transcript exists then choose that
            if manual_transcript == None:
                manual_transcript = transcript
        else:
            # Choose the auto generated transcript as a fallback
            if auto_generated_transcript == None:
                auto_generated_transcript = transcript

    # Return the manual one if exists else return autogenerated one
    if manual_transcript: return manual_transcript
    else: return auto_generated_transcript

"""---------------------------------------------------------------------------------------------------------------"""
# FUNCTION TO GET TIMESTAMPS
def format_time(seconds):
    return str(timedelta(seconds=int(seconds)))

"""---------------------------------------------------------------------------------------------------------------"""
# FUNCTION TO GET THE TRANSCRIPT
async def get_transcript(transcript, user, video_id):
    # Safety check
    if transcript is None:
        raise ValueError("No subtitle found for this YouTube URL")
    
    try:
        # Get transcript data
        data = transcript.fetch()

        # Set the output directory
        out_dir = Path(f"data/transcripts")
        out_dir.mkdir(parents=True, exist_ok=True)

        # Set the output path
        out_path = Path(f"{out_dir}/{video_id}_transcript.txt")

        # Write the transcript onto the file
        with out_path.open('w', encoding='utf-8', newline="\n") as f:
            for entry in data:
                formatted_time = format_time(entry.start)
                text = entry.text
                f.write(f"{formatted_time} : {text}\n")

        return str(out_path)
    
    except Exception as e:
        raise ValueError(f"Error occured : {e}")

"""---------------------------------------------------------------------------------------------------------------"""
# FUNCTION TO FETCH THE TRANSCRIPT FOR NOTES PROCESS
async def fetch_transcript_for_notes(user, video_id):

    # GET DATA FROM DB IF ALREADY EXISTS
    #########################################################################

    # Check if a request exists for the same video id
    session = SessionLocal()
    prev_request = session.query(ReusableRequests).filter(
        (ReusableRequests.video_id == video_id) & 
        (ReusableRequests.type=="Transcript")
    ).first()
    
    # Check if the transcript file exists
    if prev_request:
        transcript_path = Path(prev_request.file_path)
        
        if transcript_path.exists():
            logger.info(f"user_id={user.id} username={user.username} | Transcript exists in db and in storage")
           
            # Send the transcript file
            try:
                return transcript_path         
            
            except Exception as e:
                logger.exception(f"⚠️ Error during extracting the transcript from db: \n{e}")

        else:
            logger.info(f"user_id={user.id} username={user.username} | Request exists but transcript doesn't exist")

    else:
        logger.info(f"user_id={user.id} username={user.username} | No previous request exists for given video id.")


    # OTHERWISE GENERATE A NEW TRANSCRIPT
    #########################################################################

    # choose a transcript option
    transcript_object = choose_transcript(video_id)

    # If no transcript return None
    if not transcript_object:
        logger.exception(f"user_id={user.id} username={user.username} | No subtitles available for url provided by user.")
        transcript = None
        return transcript
    
    # Get the transcript if available
    try:
        transcript_path = await get_transcript(transcript_object, user, video_id)
        logger.info(f"user_id={user.id} username={user.username} | Transcript generated successfuly for video id {video_id}")
    except Exception as e:
        logger.exception(f"user_id={user.id} username={user.username} | Error while getting transcript.")


    # RETURN THE TRANSCRIPT
    #########################################################################
    return transcript_path






    

